server:
  port: 8080

app:
  security:
    trust-inbound-headers: false
    public-routes:
      - "/v1/auth/**"
      - "/webhook/**"
      - "actuator/**"

  rate-limit:
    method: fixed
    use-case:
      api-key:
        requests-per-minute: 60

spring:
  cloud:
    gateway:
      server:
        webmvc:
          routes:
            - id: merchant-service
              uri: lb://merchant-service
              predicates:
                - Path=/v1/auth/**, /v1/merchants/**

            - id: payment-service
              uri: lb://payment-service
              predicates:
                - Path=/v1/payments/**, /v1/orders/**

            - id: vault-service
              uri: lb://vault-service
              predicates:
                - Path=/v1/vault/**

            - id: operations-service
              uri: lb://operations-service
              predicates:
                - Path=/webhook/**

jwt:
  secret-key: only-for-dev-env-fduagsdiudiuadiuasiduavsduvu67etdhguhd9w8rdyw98fhoishncfijfdc90njsc
